server:
  port: 8003
  servlet:
      context-path: /cs
#服务名称
spring:
  application:
    name: consumer-service
#向eureka进行注册
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
feign:
  compression:
    request:
      enabled: true   #开启请求压缩
      mime-types: text/html,application/json   #设置压缩的数据类型,默认也是如此
      min-request-size: 2048  #设置触发压缩额最下限，默认也是如此
    response:
      enabled: true   #开启响应压缩